kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  labels:
    tier: controller
# - role: worker
#   labels:
#     tier: backend
# - role: worker
#   labels:
#     tier: backend